import {
    uniLayerGroupMonochrome,
    uniCarWash,
    uniDashboard,
    uniClipboardNotes,
    uniServerAlt,
    uniUsersAlt,
    uniSearch,
    uniTimes,
    uniArrowRight,
    uniPlusSquare,
    uniPlus,
    uniPadlock,
    uniLockOpenAlt,
    uniEye,
    uniEyeSlash,
    uniCircle,
    uniCheckCircle,
} from 'vue-unicons/dist/icons'

export default [
    uniLayerGroupMonochrome,
    uniCarWash,
    uniDashboard,
    uniClipboardNotes,
    uniServerAlt,
    uniUsersAlt,
    uniSearch,
    uniTimes,
    uniArrowRight,
    uniPlusSquare,
    uniPlus,
    uniPadlock,
    uniLockOpenAlt,
    uniEye,
    uniEyeSlash,
    uniCircle,
    uniCheckCircle
]